### PR TITLE
Fix README.md link

### PR DESCRIPTION
**Pull request by jeromemarc**
Current link points to 404

### CODE REVIEW

**Review by abellotti — APPROVED** [review]

**Comment by abellotti** [comment]
@jeromemarc can you recreate the PR, but not from a fork.   we need to merge PRs from branches off the main repo to be able have the right tokens for quay. Thanks.

**Comment by jeromemarc** [comment]
@abellotti @gtanzillo one of your can probably re-create the fix. I can only offer a PR from the fork with my permissions.

**Comment by abellotti** [comment]
no problem @jeromemarc we can do that.   Thank you for the fix !!

**Comment by abellotti** [comment]
fix here https://github.com/RedHatInsights/rhproxy-engine/pull/65 for main repo branch

**Pull request closed without merging**
